# Generated by Django 5.2.5 on 2025-09-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='additemstbl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=100)),
                ('Itemqunatity', models.CharField(max_length=100)),
                ('Itemprice', models.CharField(max_length=100)),
                ('Ifile', models.FileField(upload_to='')),
            ],
        ),
    ]
