# Generated by Django 5.2.5 on 2025-09-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_additemstbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additemstbl',
            name='Ifile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
