# Generated by Django 5.2.5 on 2025-09-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_additemstbl_ifile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additemstbl',
            name='Ifile',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
