# Generated by Django 5.2.5 on 2025-09-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_additemstbl_ifile'),
    ]

    operations = [
        migrations.AddField(
            model_name='additemstbl',
            name='customermobile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='additemstbl',
            name='customername',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
