# Generated by Django 5.2.5 on 2025-09-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_additemstbl_customermobile_additemstbl_customername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additemstbl',
            name='Itemqunatity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
