# Generated by Django 5.2.5 on 2025-10-02 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_additemstbl_itemqunatity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additemstbl',
            old_name='Itemqunatity',
            new_name='Itemquantity',
        ),
    ]
