# Generated by Django 5.2.5 on 2025-10-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_itemqunatity_additemstbl_itemquantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='customertbl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customername', models.CharField(max_length=100)),
                ('customermobile', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='additemstbl',
            name='customermobile',
        ),
        migrations.RemoveField(
            model_name='additemstbl',
            name='customername',
        ),
    ]
