# Generated by Django 5.2.5 on 2025-10-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_customertbl_remove_additemstbl_customermobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additemstbl',
            name='customermobile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='additemstbl',
            name='customername',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
