# Generated by Django 5.2.5 on 2025-10-02 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_additemstbl_customermobile_additemstbl_customername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additemstbl',
            name='customermobile',
        ),
        migrations.RemoveField(
            model_name='additemstbl',
            name='customername',
        ),
    ]
