# Generated by Django 5.2.5 on 2025-10-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_additemstbl_customermobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additemstbl',
            name='Itemquantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
