# Generated by Django 5.2.5 on 2025-10-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_additemstbl_itemquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additemstbl',
            name='Ifile',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='additemstbl',
            name='Itemprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='additemstbl',
            name='Itemquantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
